# -*- coding: utf-8 -*-
"""file1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tAOtSU-ui7wz_6UPDR25VM5GkkGqqO7O
"""

print("heloo world!")